# Generated by Django 2.1.3 on 2018-12-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_auto_20181203_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readed_num',
            field=models.IntegerField(default=0, verbose_name='被访问次数'),
        ),
    ]
