# Generated by Django 2.1.3 on 2018-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_blog_readed_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
    ]
