# Generated by Django 2.1.3 on 2018-12-03 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_auto_20181203_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
    ]
