# Generated by Django 2.1.3 on 2018-12-03 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0010_auto_20181203_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
